"""strengthen accounting models

Revision ID: 80826bf18053
Revises: b24e856db049
Create Date: 2026-08-24 21:02:38.077006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80826bf18053'
down_revision: Union[str, Sequence[str], None] = 'b24e856db049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_journal_entries_currency', 'journal_entries', "currency IN ('IRR', 'USD', 'EUR', 'GBP')")
    op.create_check_constraint('ck_journal_lines_non_negative', 'journal_lines', 'debit >= 0 AND credit >= 0')
    op.create_check_constraint('ck_journal_lines_not_both', 'journal_lines', 'NOT (debit > 0 AND credit > 0)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_journal_lines_not_both', 'journal_lines', type_='check')
    op.drop_constraint('ck_journal_lines_non_negative', 'journal_lines', type_='check')
    op.drop_constraint('ck_journal_entries_currency', 'journal_entries', type_='check')
    # ### end Alembic commands ###
